#!/bin/bash
#press w
echo -ne "\x1a\x01" > /dev/udp/localhost/32008
#also works, but results in long keypress due to -q1 one second delay on exit
#echo -ne "\x1a\x01" | nc localhost -q 1 -u 32008

sleep 0.2s

#release w
echo -ne "\x1a\x00" | nc localhost -q 1 -u 32008
#also works
#echo -ne "\x1a\x00" > /dev/udp/localhost/32008
